### ISSUE TITLE
Can't move rigidbodies in engine's viewport.

### ISSUE THREAD

**Issue by russinet** [z80/godot4_bullet_gdextension#1]
Inside of the game engine, I can't move rigidbodies when bullet physics is enabled with the transform gizmos. This makes level design impossible with rigid bodies. Right now, I need to switch back to godot physics, restart the editor, then place all the physical props in the scene, then switch back to bullet physics, then restart again. This becomes very cumbersome and makes iteration impossible.

**Comment by z80** [comment]
Thanks for the feedback, @russinet! Sorry for inconvenience! I'll check what's going on with moving bodies! Would you please let me know which executable exactly you are using, what does the version window say exactly?

**Comment by russinet** [comment]
Oh no, I am very much grateful for this plugin's existence so I'm not complaining. As for the version, I believe it's v4.0.2.stable.commit_b49f801f3. I've downloaded the latest binaries from your repo and compiled them myself.

**Comment by z80** [comment]
@russinet thank you for the details! I'm on it, will try to fix the issue...

**Comment by z80** [comment]
Hello @russinet! I appreciate you reporting the bug! I believe I've fixed it. I can drag rigid bodies when Bullet is selected now. Please see https://github.com/z80/ignition/releases/tag/commit_cd4f85694 and associated release.

Please let me know if something isn't working!
